# Generated by Django 4.2 on 2023-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='xxx', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='pho',
            field=models.CharField(default='23283957', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('manager', 'manager'), ('customer', 'customer')], default='customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
