# Generated by Django 4.2 on 2023-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_address_alter_user_pho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='xxx', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='pho',
            field=models.CharField(default='xxx', max_length=30),
        ),
    ]
