# Generated by Django 4.1.7 on 2023-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Syria / Latakia', max_length=250),
        ),
    ]
