# Generated by Django 4.2 on 2023-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
